+function(){var f;var k=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},l=function(a){if(k(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&k(a))return a;return null},n=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},q=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},r=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var u=function(a,b){return a.x*b.x+a.y*b.y},w=function(a,b){return v(b,u(a,b))},v=function(a,b){return x(a.x*b,a.y*b)},x=function(a,b){return{x:a,y:void 0!==b?b:a}};var y=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Da=function(a,c,g){for(var p=Array(arguments.length-2),h=2;h<arguments.length;h++)p[h-2]=arguments[h];return b.prototype[c].apply(a,p)}};var z=["-ms-","-moz-","-webkit-",""],A=function(a,b,c){for(var d,e,g=0;g<z.length;++g)d=z[g]+b,e=""+c,a.style.setProperty(d,e)};var B=function(a){setTimeout(a,0)};var C=function(a,b,c){var d;c?(d=document.createEvent("CustomEvent"),d.initCustomEvent(a,!0,!0,c)):(d=document.createEvent("Event"),d.initEvent(a,!0,!0));b.dispatchEvent(d);return d},D=function(a,b){B(function(){C("autoplayended",a,b)})},E=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var F=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var G=function(a,b){this.o=a;this.u=null;this.Ca=b;this.L=!1};
G.prototype.play=function(a,b,c){if(this.o.frameCount&&null==this.u){b=b||"forwards";var d;c?(d=Math.floor(a/c),a=c):(d=this.o.frameCount,a/=d);var e=[],g=this.o.currentIndex-1;c=g;for(var p=0;p<d;p++){if(0<p||!this.Ca)c=H(c+I(b,1),this.o.frameCount);e.push(c)}b=function(){if(e.length){var a=e.shift();this.L=!0;this.o.goToFrame(a+1);this.L=!1;var b=this.o;C("frameautoplayed",b,{id:a+1||b.currentIndex})}else this.stop(!0),this.o.goToFrame(g+1)}.bind(this);this.u=setInterval(b,a);setTimeout(b)}};
G.prototype.stop=function(a){!this.L&&this.u&&(clearInterval(this.u),D(this.o,{completed:!!a}),this.u=null)};
var J=function(a){var b=document.createElement("img","gwd-image");b.setAttribute("source",a);return b},K=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(J(F(a[c])))}return b},L=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];"img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")&&(null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling"))}},M=function(a,b){for(var c=b.length,d=b.splice(0,c),e,g=0;g<c;g++)e=d[g],"frameshown"==
e?C(e,a,{id:a.currentIndex}):C(e,a)},I=function(a,b){return"left"==a||"backwards"==a?-b:b},H=function(a,b){return(a%b+b)%b};var N=function(){};y(N,HTMLElement);f=N.prototype;f.createdCallback=function(){this.f=[];this.b=null;this.a=0;this.m=1;this.w=new G(this,!0);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.la.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.oa.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.na.bind(this)})};f.attributeChangedCallback=function(){};f.getFrame=function(a){if(0!=this.a)return this.f[a-1]};f.gwdLoad=function(){};
f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.a&&(a>this.a?a=this.a:1>a&&(a=1),this.Z(a,b))};f.Z=function(a){this.b=a-1};var O=function(a,b,c,d){if(null!=a.b){var e=H(a.b+I(b,a.m||1),a.m*Math.ceil(a.a/a.m));((null!=d?d:1)||!("forwards"==b&&e<a.b||"backwards"==b&&e>a.b))&&a.goToFrame(e+1,c||"slide")}};f=N.prototype;f.goBackwards=function(a,b){return O(this,"backwards",a,b)};f.goForwards=function(a,b){return O(this,"forwards",a,b)};
f.rotateOnce=function(a,b){this.w.play(a||0,b)};f.stopRotation=function(){this.w.stop()};f.la=function(){return 0<this.a?this.b+1:void 0};f.oa=function(){return this.m};f.na=function(){return this.a};var P=function(){};y(P,N);
P.prototype.createdCallback=function(){P.R.createdCallback.call(this);this.M=!1;this.N=this.c=null;if(this.Y=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.s=x(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.K=a;this.l=!1;this.g=null;this.ca=this.va.bind(this);this.ea=this.xa.bind(this);this.aa=this.ta.bind(this);this.ba=this.ua.bind(this);this.da=this.wa.bind(this);this.V=this.qa.bind(this);this.ka=this.Aa.bind(this);this.ja=this.za.bind(this);
this.ia=this.ya.bind(this);this.X=this.ra.bind(this);this.fa=this.sa.bind(this);this.G=C.bind(null,"firstinteraction",this);this.S=!1;this.P=[];this.v=M.bind(null,this,this.P);this.ga=this.ha=this.D=this.U=this.T=0;this.J=1;this.F=[];this.I=0;this.Ba=.7;this.B=0;this.C=!1;this.O=x(0);this.H=x(0);this.h=null;this.i=this.$=-1;this.W=[];this.A=x(-1,-1);a="y"==this.getAttribute("swipe-axis");this.j=x(a?0:1,a?1:0);Object.defineProperty(this,"firstVisibleFrameIndex",{enumerable:!0,get:this.ma.bind(this)});
Object.defineProperty(this,"lastVisibleFrameIndex",{enumerable:!0,get:this.pa.bind(this)})};
P.prototype.attachedCallback=function(){var a=this.K;a.addEventListener("pointerover",this.ea,!1);a.addEventListener("pointerout",this.ca,!1);a.addEventListener("pointermove",this.aa,!1);a.addEventListener("track",this.ka,!1);a.addEventListener("trackend",this.ja,!1);a.addEventListener("tap",this.ia,!1);this.addEventListener("frametap",this.X,!1);this.addEventListener("transitionend",this.v,!1);this.addEventListener("webkitTransitionEnd",this.v,!1);if("function"==typeof this.gwdLoad&&"function"==
typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=l(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
P.prototype.detachedCallback=function(){var a=this.K;a.removeEventListener("pointerover",this.ea,!1);a.removeEventListener("pointerout",this.ca,!1);a.removeEventListener("pointermove",this.aa,!1);a.removeEventListener("track",this.ka,!1);a.removeEventListener("trackend",this.ja,!1);a.removeEventListener("tap",this.ia,!1);this.removeEventListener("frametap",this.X,!1);this.removeEventListener("transitionend",this.v);this.removeEventListener("webkitTransitionEnd",this.v)};
P.prototype.attributeChangedCallback=function(a){switch(a){case "images":this.f=K(this.getAttribute("images"));Q(this);R(this);break;case "scaling":L(this.f,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":S(this);R(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":T(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":T(this);
R(this);break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":R(this)}};
var T=function(a){var b=n(a,"num-frames-to-display",1),c=n(a,"frame-snap-interval",1),d=n(a,"transition-duration",600),e=n(a,"frame-width",-1),g=n(a,"frame-height",-1),p;p=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"";var h=q(a,"autoplay-duration",3E3),m=q(a,"autoplay-step-interval",0);a.A.x=e;a.A.y=g;-1!=u(a.A,a.j)?b=-1:0<b&&c>b&&(c=b);a.W=p.split(/,/g);a.i=b;a.m=c;a.D=d;a.T=h;a.U=m},R=function(a){var b=x(a.clientWidth,a.clientHeight);a.h&&(b.y-=36,a.N.style.height=b.y+"px");var c=a.j,
d=v(c,n(a,"offset",0)),e=q(a,"swipe-threshold-ratio",.1),g=q(a,"swipe-committed-threshold-ratio",.5),p=a.i,h=a.A,h=x(-1==h.x?b.x:h.x,-1==h.y?b.y:h.y),m=x(0);1<p&&(m=v(c,p-1),m=x(m.x*d.x,m.y*d.y),m=w(x((b.x-m.x)/p,(b.y-m.y)/p),c),m.x&&(h.x=m.x),m.y&&(h.y=m.y));var p=n(a,"start-frame",2<a.i?1+Math.ceil(a.i/2-1):1),Z=a.hasAttribute("disable-gesture"),m=w(x(h.x+d.x,h.y+d.y),c),t;t=1+2*Math.floor((u(c,b)-u(c,h))/(2*u(c,m)));if(1>t||!isFinite(t))t=1;b=x((b.x-h.x)/2,(b.y-h.y)/2);0<a.i&&0==a.i%2&&(d=w(x(h.x+
d.x,h.y+d.y),c),b.x-=.5*d.x,b.y-=.5*d.y,t+=1);a.H=h;a.O=b;a.J=t;a.B=u(m,a.j);a.l=Z;a.ha=u(h,c)*e;a.ga=u(h,c)*g;e=w(b,x(c.y,c.x));for(d=0;d<a.a;d++)g=a.f[d].style,g.left=e.x+"px",g.top=e.y+"px",g.width=h.x+"px",g.height=h.y+"px",e.x+=m.x,e.y+=m.y;a.s=x(0);a.c&&(U(a,0,0,0),c=w(b,c),a.c.style.left=c.x+"px",a.c.style.top=c.y+"px");a.b=null;a.goToFrame(p,"none")};f=P.prototype;f.gwdIsLoaded=function(){return this.M};
f.gwdLoad=function(){if(!this.M&&!this.c){var a;if(this.Y)a=K(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.f=a;Q(this)}};f.goBackwards=function(a,b){return P.R.goBackwards.call(this,a,null!=b?b:!1)};f.goForwards=function(a,b){return P.R.goForwards.call(this,a,null!=b?b:!1)};
f.Z=function(a,b){var c=a-1,c=c-c%this.m,c=c+Math.floor((this.m-1)/2);c>=this.a&&(c=this.a-1);var d=this.b;this.b=c;c=v(this.j,-this.B*this.b);U(this,"none"!=b?this.D:0,c.x,c.y);this.s=c;if(this.I)for(var c=Math.floor((this.J-1)/2),e=0;e<this.J;e++){var g=this.b-c+e;if(!(0>g||g>=this.a||this.F[g]||(this.F[g]=!0,--this.I))){this.P.push("allframesviewed");break}}d!=this.b&&(V(this,this.b+1),this.P.push("frameshown"));this.S||this.v()};
var U=function(a,b,c,d){a.S=0<b;A(a.c,"transition","all "+b+"ms");A(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},Q=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.h=null;a.c&&(a.c.removeEventListener("pageload",a.fa,!1),a.c.removeEventListener("mouseover",a.da,!0),a.c.removeEventListener("mouseout",a.ba,!0),a.c.removeEventListener("click",a.V,!0));for(var b=a.f,c=document.createElement("div","gwd-page"),d,e=0;e<b.length;++e)d=b[e],A(d,"user-select","none"),d.classList.add("frame"),
c.appendChild(d);E(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.fa,!1);a.c.addEventListener("mouseover",a.da,!0);a.c.addEventListener("mouseout",a.ba,!0);a.c.addEventListener("click",a.V,!0);L(a.f,a.getAttribute("scaling"));a.a=a.f.length;b=document.createElement("div");a.N=b;b.className="matte";b.appendChild(c);a.appendChild(a.N);a.appendChild(a.K)};
P.prototype.sa=function(a){a.target===this.c&&(this.M=!0,this.I=this.a,this.F=[],T(this),S(this),R(this),C("allframesloaded",this),this.hasAttribute("autoplay")&&this.w.play(this.T,"forwards",this.U),C("ready",this))};P.prototype.rotateOnce=function(a,b){this.w.play(a||this.D,b)};
var X=function(a,b){var c=a.a;if(c){var d=a.b,e=W(a,b);a.goToFrame(e+1);d!=e&&(0==e?C("reachleftend",a):e==c-1&&C("reachrightend",a))}},S=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.h;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.h=document.createElement("gwd-gallerynavigation"),a.h.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.h)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.h),a.h=null);a.h&&(r(a,"navigation-highlight",a.h,"highlight"),
r(a,"navigation-thumbnails",a.h,"use-thumbnails"))},W=function(a,b){var c=a.b;Math.abs(b)>a.ha&&(c=0>b?c+a.m:c-a.m);0>c?c=0:c>=a.a&&(c=a.a-1);return c},V=function(a,b){a.$!=b&&(a.$=b,C("frameactivated",a,{id:b||a.currentIndex}))};
P.prototype.Aa=function(a){if(!this.l&&(this.G&&(this.G(),this.G=null),!this.C))if(this.stopRotation(),a=u(x(a.dx,a.dy),this.j),V(this,W(this,a)+1),Math.abs(a)>this.ga)X(this,a),this.C=!0;else{if(0<a&&0===this.b||0>a&&this.b===this.a-1)a-=a*this.Ba;U(this,0,this.s.x+this.j.x*a,this.s.y+this.j.y*a)}};P.prototype.za=function(a){this.l||(this.C?this.C=!1:X(this,u(x(a.dx,a.dy),this.j)))};
var Y=function(a,b){var c=a.getBoundingClientRect(),c=x(b.clientX-c.left,b.clientY-c.top),d=a.j,e=x(d.y,d.x),d=u(e,c),g=u(e,a.O),e=u(e,a.H);if(d<g||d>g+e)return null;d=a.j;c=u(d,c)-u(d,a.s)-u(d,a.O);d=Math.floor(c/a.B);return 0>d||d>=a.a||c%a.B>u(a.j,a.H)?null:d};f=P.prototype;f.ya=function(a){this.l||(this.stopRotation(),a=Y(this,a),null!=a&&C("frametap",this,{element:this.f[a],id:a+1}))};f.ra=function(a){(a=a.detail&&a.detail.id)&&(a=this.W[a-1])&&!C("frameexit",this,{url:a}).detail.handled&&window.open(a)};
f.va=function(){this.l||null==this.g||(C("framemouseout",this,{element:this.f[this.g],id:1+this.g}),this.g=null)};f.xa=function(a){this.l||(a=Y(this,a),a!=this.g&&(null!=this.g&&C("framemouseout",this,{element:this.f[this.g],id:1+this.g}),null!=a&&C("framemouseover",this,{element:this.f[a],id:1+a}),this.g=a))};
f.ta=function(a){this.l||(a=Y(this,a),a!=this.g&&(null!=this.g&&C("framemouseout",this,{element:this.f[this.g],id:1+this.g}),null!=a&&C("framemouseover",this,{element:this.f[a],id:1+a}),this.g=a))};f.wa=function(a){this.l&&a.target.classList.contains("frame")&&C("framemouseover",this,{element:a.target,id:1+this.f.indexOf(a.target)})};f.ua=function(a){this.l&&a.target.classList.contains("frame")&&C("framemouseout",this,{element:a.target,id:1+this.f.indexOf(a.target)})};
f.qa=function(a){this.l&&a.target.classList.contains("frame")&&C("frametap",this,{element:a.target,id:1+this.f.indexOf(a.target)})};f.ma=function(){if(0<this.i&&0<this.a)return Math.max(1,1+this.b-Math.floor((this.i-1)/2))};f.pa=function(){if(0<this.i&&0<this.a)return Math.min(this.a,1+this.b-Math.floor((this.i-1)/2)+this.i-1)};document.registerElement("gwd-swipegallery",{prototype:P.prototype});}()
